[[quickstart-publiccloud-setup]]
= Setting Up


Public clouds provide {productname} under a Bring Your Own Subscription (BYOS) model.
This means that you must register instances with the {scc}.
For more information about registering {productname} with {scc}, see xref:installation:general-requirements.adoc[].

Depending on the public cloud framework you are using, you can locate the {productname} images by searching for the  keywords ``suse``, ``manager``, or ``BYOS``.

.SUSE Manager Image Names
[cols="1,1", options="header"]
|===
| Provider              | Image Name
| Amazon EC2            |
| Google Compute Engine |
| Microsoft Azure       |
|===

Select a public cloud instance type with at least:

* 32{nbsp}GB RAM
* 8 cores

 For more information about hardware requirements, see xref:installation:hardware-requirements.adoc[].

[WARNING]
====
When running {productname} on public clouds, make sure you apply security measures to limit access to the right persons. A world-accessible {productname} would give access to your infrastructure to anyone"
====



.Procedure: Obtaining Your SCC Organization Credentials
. Navigate to https://scc.suse.com/login in your Web browser.
. Log in to your SCC account, or follow the prompts to create a new account.
. If you have not yet done so, click btn:[Connect to an Organization] and type or search for your organization.
. Click btn:[Manage my Organizations] and select your organization from the list by clicking on the organization name.
. Click the btn:[Organization] tab, and then select the btn:[Organization Credentials] tab.
. Record your login information for use during {productname} setup.

Depending on your organization's setup, you might also need to activate your subscription, using the btn:[Activate Subscriptions] menu.



To access the {productname} {webui}, configure the network access controls to allow HTTPS.

Amazon EC2:

----
TBD
----

Google Compute Engine:

----
TBD
----

Microsoft Azure:

----
TBD
----


We recommend that the repositories and the database for {productname} are stored on a separate storage volume.
For details, see xref:installation:pubcloud-requirements.adoc[].
